name: main

on:
  push:
    branches: ["main"]

jobs:
  build-dist:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4

      - uses: jessehouwing/actions-semver-checker@v1
        with:
          check-minor-version: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: |
          npm run build --configuration=production
          cp -R ./dist ${HOME}

      - name: Store dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist_folder
          path: ./dist

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-dist

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #      - name: Login to Docker Hub
      #        uses: docker/login-action@v3
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist_folder
          path: ./dist

      - name: Folder debug
        shell: bash
        run: |
          pwd
          echo "---"
          ls -al
          echo "---"
          ls -al ./dist
          echo "---"
          ls -al ./dist/cities-of-europe
          echo "---"
          ls -al ./dist/cities-of-europe/browser

      # TODO push also
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: holgerstolzenberg/cities-of-europe:latest
          push: false
